Controllers/ZoosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zoo_w57047.Database;
using Zoo_w57047.Entity;
using Zoo_w57047.Models;

namespace Zoo_w57047.Controllers
{
    public class ZoosController : Controller
    {
        private readonly ZooContext _context;

        public ZoosController(ZooContext context)
        {
            _context = context;
        }

        // GET: Zoos
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;

            IQueryable<Zoo> source = _context.Zoos.Include(x => x.Animals).Include(x => x.Aviaries);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Zoos = items
            };

            return View(viewModel);
        }

        // GET: Zoos/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zoo = await _context.Zoos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (zoo == null)
            {
                return NotFound();
            }

            return View(zoo);
        }

        // GET: Zoos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Zoos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Adress,TicketPrice")] Zoo zoo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(zoo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(zoo);
        }

        // GET: Zoos/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zoo = await _context.Zoos.FindAsync(id);
            if (zoo == null)
            {
                return NotFound();
            }
            return View(zoo);
        }

        // POST: Zoos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Adress,TicketPrice")] Zoo zoo)
        {
            if (id != zoo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(zoo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ZooExists(zoo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(zoo);
        }

        // GET: Zoos/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var zoo = await _context.Zoos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (zoo == null)
            {
                return NotFound();
            }

            return View(zoo);
        }

        // POST: Zoos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var zoo = await _context.Zoos.FindAsync(id);
            _context.Zoos.Remove(zoo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ZooExists(long id)
        {
            return _context.Zoos.Any(e => e.Id == id);
        }
    }
}

Views/Zoos/Create.cshtml
@model Zoo_w57047.Entity.Zoo

@{
    ViewData["Title"] = "Create";
}

<h1 class="page-title">New location is here!</h1>
<div style="text-align: end;">
    <input class="btn btn-dark" type="button" value="Back to List" onclick="location.href='@Url.Action("Index", "Zoos")'" />
</div>
<hr />
<div class="row-12" style="display:flex;">
    <div class="col-6">
        <img src="~/assets/images/Zoo.png" style="max-width: 100%;"/>
    </div>
    <div class="col-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketPrice" class="control-label"></label>
                <input asp-for="TicketPrice" class="form-control" />
                <span asp-validation-for="TicketPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Zoos/Delete.cshtml
@model Zoo_w57047.Entity.Zoo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zoo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Zoos/Details.cshtml
@model Zoo_w57047.Entity.Zoo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Zoo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketPrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Zoos/Edit.cshtml
@model Zoo_w57047.Entity.Zoo

@{
    ViewData["Title"] = "Edit";
}

<h1 class="page-title">Is something changed?</h1>
<div style="text-align: end;">
    <input class="btn btn-dark" type="button" value="Back to List" onclick="location.href='@Url.Action("Index", "Zoos")'" />
</div>
<hr />
<div class="row-12" style="display:flex;">
    <div class="col-6">
        <img src="~/assets/images/paddock.png" style="max-width: 100%;" />
    </div>
    <div class="col-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketPrice" class="control-label"></label>
                <input asp-for="TicketPrice" class="form-control" />
                <span asp-validation-for="TicketPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Zoos/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Zoos";
}

<h1 class="page-title">Our zoos</h1>

<div style="text-align: end;">
    <input class="btn btn-success" style="margin: 10px;" type="button" value="Add new location" onclick="location.href='@Url.Action("Create", "Zoos")'" />
</div>


<table class="table">
    <thead>
        <tr>
            <th>
                №
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zoos.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zoos.FirstOrDefault().Adress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zoos.FirstOrDefault().TicketPrice)
            </th>
            <th style="text-align:end">Actions</th>
        </tr>
    </thead>
    <tbody>
        @{int i = 1;}
        @foreach (var item in Model.Zoos)
        {
        <tr>
            <td>
                @i @{i++;}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPrice)
            </td>
            <td style="text-align:end">
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-edit"><i class="far fa-edit"></i></a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-info"><i class="fas fa-info"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-danger"><i class="far fa-trash-alt"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="fas fa-angle-left"></i>
        Previous
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Next
        <i class="fas fa-angle-right"></i>
    </a>
}