Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zoo_w57047.Database;
using Zoo_w57047.Entity;
using Zoo_w57047.Enums;
using Zoo_w57047.Models;

namespace Zoo_w57047.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly ZooContext _context;

        public AnimalsController(ZooContext context)
        {
            _context = context;
        }

        // GET: Animals
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;

            IQueryable<Animal> source = _context.Animals.Include(x => x.Aviary);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Animals = items
            };
            return View(viewModel);
        }

        // GET: Animals/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animals/Create
        public IActionResult Create()
        {
            var animalTypes = from AnimalType d in Enum.GetValues(typeof(AnimalType))
                              select new { ID = (int)d, Name = d.ToString() };
            ViewData["animalTypes"] = new SelectList(animalTypes, "ID", "Name");

            var AvailableAviaries = _context.Aviaries.Include(x => x.Animals).Where(x => x.MaxAnimals > x.Animals.Count).ToList();

            NewAnimal viewModel = new NewAnimal
            {
                Aviaries = AvailableAviaries
            };

            return View(viewModel);
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type,Name,DateOfBirth,Country,ArrivalDate,Description,AviaryId")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(animal);
        }

        // GET: Animals/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals.FindAsync(id);
            if (animal == null)
            {
                return NotFound();
            }

            var animalTypes = from AnimalType d in Enum.GetValues(typeof(AnimalType))
                              select new { ID = (int)d, Name = d.ToString() };
            ViewData["animalTypes"] = new SelectList(animalTypes, "ID", "Name");
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Type,Name,DateOfBirth,Country,ArrivalDate,Description")] Animal animal)
        {
            if (id != animal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(animal);
        }

        // GET: Animals/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var animal = await _context.Animals.FindAsync(id);
            _context.Animals.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(long id)
        {
            return _context.Animals.Any(e => e.Id == id);
        }
    }
}

Controllers/AviariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zoo_w57047.Database;
using Zoo_w57047.Entity;
using Zoo_w57047.Enums;
using Zoo_w57047.Models;

namespace Zoo_w57047.Controllers
{
    public class AviariesController : Controller
    {
        private readonly ZooContext _context;

        public AviariesController(ZooContext context)
        {
            _context = context;
        }

        // GET: Aviaries
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;

            IQueryable<Aviary> source = _context.Aviaries.Include(x => x.Animals);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Aviaries = items
            };
            return View(viewModel);
        }

        // GET: Aviaries/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aviary = await _context.Aviaries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aviary == null)
            {
                return NotFound();
            }

            return View(aviary);
        }

        // GET: Aviaries/Create
        public IActionResult Create()
        {
            var aviaryTypes = from AviaryType d in Enum.GetValues(typeof(AviaryType))
                            select new { ID = (int)d, Name = d.ToString() };
            var aviaryConditions = from AviaryCondition d in Enum.GetValues(typeof(AviaryCondition))
                              select new { ID = (int)d, Name = d.ToString() };
            ViewData["AviaryType"] = new SelectList(aviaryTypes, "ID", "Name");
            ViewData["AviaryConditions"] = new SelectList(aviaryConditions, "ID", "Name");

            var Zoos = _context.Zoos.Where(x => x.Id == x.Id).ToList();

            NewAviary viewModel = new NewAviary
            {
                Zoos = Zoos
            };

            return View(viewModel);
        }

        // POST: Aviaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Condition,MaxAnimals,Type,ZooId")] Aviary aviary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aviary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aviary);
        }

        // GET: Aviaries/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aviary = await _context.Aviaries.FindAsync(id);
            if (aviary == null)
            {
                return NotFound();
            }

            var aviaryTypes = from AviaryType d in Enum.GetValues(typeof(AviaryType))
                              select new { ID = (int)d, Name = d.ToString() };
            var aviaryConditions = from AviaryCondition d in Enum.GetValues(typeof(AviaryCondition))
                                   select new { ID = (int)d, Name = d.ToString() };
            ViewData["AviaryType"] = new SelectList(aviaryTypes, "ID", "Name");
            ViewData["AviaryConditions"] = new SelectList(aviaryConditions, "ID", "Name");

            return View(aviary);
        }

        // POST: Aviaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Condition,MaxAnimals,Type")] Aviary aviary)
        {
            if (id != aviary.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aviary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AviaryExists(aviary.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aviary);
        }

        // GET: Aviaries/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aviary = await _context.Aviaries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aviary == null)
            {
                return NotFound();
            }

            return View(aviary);
        }

        // POST: Aviaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var aviary = await _context.Aviaries.FindAsync(id);
            _context.Aviaries.Remove(aviary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AviaryExists(long id)
        {
            return _context.Aviaries.Any(e => e.Id == id);
        }
    }
}

Views/Animals/Create.cshtml
@model Zoo_w57047.Models.NewAnimal

@{
    ViewData["Title"] = "Create";
}

<h1 class="page-title">New resident's data</h1>

<div style="text-align: end;">
    <input class="btn btn-dark" type="button" value="Back to List" onclick="location.href='@Url.Action("Index", "Animals")'" />
</div>

<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="row">
    <form asp-action="Create" class="col-12" style="display:contents;">
        <div class="col-6">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" class="form-control" asp-items="ViewBag.AnimalTypes"></select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group col-6">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <label asp-for="DateOfBirth" class="control-label"></label>
                    <input value="@DateTime.Now" type="date" asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group col-6">
                    <label asp-for="ArrivalDate" class="control-label"></label>
                    <input value="@DateTime.Now" type="date" asp-for="ArrivalDate" class="form-control" />
                    <span asp-validation-for="ArrivalDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="5" class="form-control" style="max-height:150px; min-height:50px;"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
        <div class="scrollbar col-6" id="style-1" style="height:450px;">
            <div class="force-overflow">
                <div class="form-group">
                    <label asp-for="Aviary" class="control-label"></label>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>

                                </th>
                                <th>
                                    Condition
                                </th>
                                <th>
                                    Animals
                                </th>
                                <th>
                                    Type
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var aviary in Model.Aviaries)
                            {
                                <tr>
                                    <td>
                                        <input type="radio" asp-for="AviaryId" value="@aviary.Id" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => aviary.Condition)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => aviary.Animals.Count)/@Html.DisplayFor(x => aviary.MaxAnimals)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => aviary.Type)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Animals/Delete.cshtml
@model Zoo_w57047.Entity.Animal

@{
    ViewData["Title"] = "Delete";
}
<h1 class="page-title">What's going on with our resident?</h1>

<div style="text-align: end;">
    <input class="btn btn-dark" type="button" value="Back to List" onclick="location.href='@Url.Action("Index", "Aviaries")'" />
</div>

<div class="row-12" style="display:flex;">
    <hr />
    <div class="col-6"  style="text-align:center;">
        <img src="~/assets/images/unnamed.png" style="max-width: 80%;" />
    </div>
    <div class="col-6">
        <dl class="row" style="margin-top:50px;">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Type)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Country)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Country)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.ArrivalDate)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ArrivalDate)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
</div>

Views/Animals/Details.cshtml
@model Zoo_w57047.Entity.Animal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Animal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Animals/Edit.cshtml
@model Zoo_w57047.Entity.Animal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Animal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="ViewBag.AnimalTypes"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDate" class="control-label"></label>
                <input asp-for="ArrivalDate" class="form-control" />
                <span asp-validation-for="ArrivalDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Animals/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Animals";
}

<h1 class="page-title">Lovely animals</h1>

<div style="text-align: end;">
    <input class="btn btn-success" style="margin: 10px;" type="button" value="Do we have new residents?" onclick="location.href='@Url.Action("Create", "Animals")'" />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                №
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().DateOfBirth).
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().ArrivalDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Animals.FirstOrDefault().Description)
            </th>
            <th style="text-align:end">Actions</th>
        </tr>
    </thead>
    <tbody>
        @{int i = 1;}
        @foreach (var item in Model.Animals)
        {
            <tr>
                <td>
                    @i @{i++;}
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td style="text-align:end">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-edit"><i class="far fa-edit"></i></a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-info"><i class="fas fa-info"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-circle btn-danger"><i class="far fa-trash-alt"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="fas fa-angle-left"></i>
        Previous
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Next
        <i class="fas fa-angle-right"></i>
    </a>
}